version: '3.7'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    networks:
      - test-network
    environment:
      - MYSQL_DATABASE=db_recruitment_task
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3307:3306"
    restart: always
  test-app:
    restart: always
    build: .
    container_name: test-app
    ports:
      - "8081:8080"
    networks:
      - test-network
    depends_on:
      - mysqldb
    links:
      - mysqldb:mysqldb
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  test-network:
    name: test-network